alexandria:
  info:
    service: "example"
    version: 0.1.0
  persistence:
    dbms:
      url: "postgres://postgres:root@postgres:5432/example_db?sslmode=disable"
      driver: "postgres"
      user: "postgres"
      password: "root"
      host: "postgres"
      port: 5432
      database: "example_db"
    mem:
      network: ""
      host: "redis"
      port: 6379
      password: ""
      database: 0
    doc:
      collection: "example_docstore"
      partition_key: "example_id"
      sort_key: "example_timestamp"
      allow_scan: true
  service:
    transport:
      http:
        host: "0.0.0.0"
        port: 8080
      rpc:
        host: "0.0.0.0"
        port: 31337
  tracing:
    # OpenTracing consumers
    zipkin:
      host: "http://zipkin:9411/api/v2/spans"
      endpoint: "0.0.0.0:8080"
      bridge: true
  event:
    kafka:
      cluster:
        # Kafka Brokers nodes
        leader:
          host: "kafka"
          port: 9092
        1:
          host: "kafka1"
          port: 9092
  cloud:
    aws:
      cognito:
        pool: "example_pool_id"
        client: "example_client_id"
  security:
    auth:
      jwt:
        secret: "example_secret_key"
